### ISSUE TITLE
IGNORE_GITIGNORED_FILES (default value true) when linter run in `project` mode

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1010]
**Describe the bug**
When `IGNORE_GITIGNORED_FILES ` is set to True (default value now since v5.0.0) and run linters in `project` mode like `jscpd` with a default TEMPLATE config file, files listed in `.gitignore` are not ignored  

**To Reproduce**
I've not yet introduced Mega-Linter (ML) on my remote repository https://github.com/llaville/graph-uml (this is my goal).
So when running ML locally without any ML configuration

1. `git clone --branch 1.0.0-rc.3 https://github.com/llaville/graph-uml.git`
2. `docker run -v $(pwd):/tmp/lint -e LOG_LEVEL=DEBUG megalinter/megalinter-php:v5`
3. See screenshot capture

**Expected behavior**
`vendor` folder should be ignored
Perharps a warning message on console that files are possibly not ignored in `project` mode 

**Screenshots**

```
[jscpd] command: ['jscpd', '--reporters', 'console,html', '--output', './report/copy-paste/', '-c', '/action/lib/.automation/.jscpd.json', '.']
[jscpd] CWD: /tmp/lint

<... much more ...>

## Processed [COPYPASTE] files
- Using [jscpd v3.3.26] https://github.com/kucherenko/jscpd/tree/master/packages/jscpd
- MegaLinter key: [COPYPASTE_JSCPD]
- Rules config: [.jscpd.json]
--Error detail:
Clone found (php):
 - vendor/graphp/graphviz/tests/GraphVizTest.php [152:19 - 159:61] (7 lines, 75 tokens)
   vendor/graphp/graphviz/tests/GraphVizTest.php [125:21 - 132:51]

<... much more ...>

┌──────────┬────────────────┬─────────────┬──────────────┬──────────────┬──────────────────┬───────────────────┐
│ Format   │ Files analyzed │ Total lines │ Total tokens │ Clones found │ Duplicated lines │ Duplicated tokens │
├──────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ php      │ 53             │ 6529        │ 43592        │ 17           │ 211 (3.23%)      │ 1972 (4.52%)      │
├──────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ markdown │ 1              │ 4           │ 49           │ 0            │ 0 (0%)           │ 0 (0%)            │
├──────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ diff     │ 1              │ 42          │ 247          │ 0            │ 0 (0%)           │ 0 (0%)            │
├──────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ markup   │ 1              │ 98          │ 1624         │ 0            │ 0 (0%)           │ 0 (0%)            │
├──────────┼────────────────┼─────────────┼──────────────┼──────────────┼──────────────────┼───────────────────┤
│ Total:   │ 56             │ 6673        │ 45512        │ 17           │ 211 (3.16%)      │ 1972 (4.33%)      │
└──────────┴────────────────┴─────────────┴──────────────┴──────────────┴──────────────────┴───────────────────┘
Found 17 clones.
HTML report saved to report/copy-paste/html/
ERROR: jscpd found too many duplicates (3.16%) over threshold (0%)
Error: ERROR: jscpd found too many duplicates (3.16%) over threshold (0%)
    at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
    at Array.forEach (<anonymous>)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

```

**Additional context**

Mega-Linter v5.1.0 -- https://github.com/megalinter/megalinter/releases/tag/v5.1.0

```
----------------------------------------------------------------------------------------------------
-------------------------------------------- MegaLinter --------------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2021-11-15T15:24:49Z
 - Image Revision: 62bbbe35
 - Image Version: v5
```

`.gitignore` file contents : https://github.com/llaville/graph-uml/blob/1.0.0-rc.3/.gitignore
```
.idea/
composer.lock
vendor/
```

**Comment by nvuillam** [comment]
Linters with cli_lint_mode = project often have their own ignore config file ( like jscpd in .jscpd.json )
As the format is not always gitignore format, I don't see a generic way to make IGNORE_GITIGNORED_FILES taken in account... do you ? :/

**Comment by llaville** [comment]
Yes, I've a solution in minds, but Mega-Linter plugin system and/or PRE-COMMANDs did not work as I'm expected to be. So currently, no solution running !
