### ISSUE TITLE
re.error: multiple repeat at position 26

### ISSUE THREAD

**Issue by Bysmyyr** [megalinter/megalinter#1022]
Hi, just drop-replaced superlinter with megalinter and got this error, any idea why?

```
/usr/local/bin/docker run --name megalintermegalinterv5_1f1b73 --label 60e226 --workdir /github/workspace --rm -e VALIDATE_ALL_CODEBASE -e DEFAULT_BRANCH -e GITHUB_TOKEN -e GITHUB_DOMAIN -e GITHUB_CUSTOM_API_URL -e LOG_LEVEL -e LINTER_RULES_PATH -e EDITORCONFIG_FILE_NAME -e FILTER_REGEX_EXCLUDE -e VALIDATE_BASH -e VALIDATE_CSS -e VALIDATE_DOCKERFILE_HADOLINT -e VALIDATE_EDITORCONFIG -e VALIDATE_GITHUB_ACTIONS -e VALIDATE_JAVASCRIPT_ES -e VALIDATE_JAVASCRIPT_STANDARD -e VALIDATE_JSCPD -e VALIDATE_KUBERNETES_KUBEVAL -e VALIDATE_MARKDOWN -e VALIDATE_NATURAL_LANGUAGE -e VALIDATE_SHELL_SHFMT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/healthcheck-core/healthcheck-core":"/github/workspace" megalinter/megalinter:v5  "-v" "/var/run/docker.sock:/var/run/docker.sock:rw"
[config] Environment variables only (no config file found in /github/workspace)
----------------------------------------------------------------------------------------------------
-------------------------------------------- MegaLinter --------------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2021-11-18T17:29:04Z
 - Image Revision: 74b801d5
 - Image Version: v5
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - megalinter.github.io
----------------------------------------------------------------------------------------------------
GITHUB_REPOSITORY: ******
GITHUB_REF: refs/pull/144/merge
GITHUB_RUN_ID: 135924


[Activation] JSX_ESLINT has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
[Activation] SWIFT_SWIFTLINT has been set inactive, as none of these files has been found: ['.swiftlint.yml']
[Activation] TSX_ESLINT has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
[Activation] TYPESCRIPT_ES has been set inactive, as none of these files has been found: ['.eslintrc.json', '.eslintrc.yml', '.eslintrc.yaml', '.eslintrc.js', '.eslintrc.cjs']
Skipped linters: ANSIBLE_ANSIBLE_LINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, CSS_SCSS_LINT, CSS_STYLELINT, DOCKERFILE_HADOLINT, EDITORCONFIG_EDITORCONFIG_CHECKER, JAVASCRIPT_ES, JAVASCRIPT_PRETTIER, JAVASCRIPT_STANDARD, JSX_ESLINT, KUBERNETES_KUBEVAL, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, MARKDOWN_REMARK_LINT, SALESFORCE_SFDX_SCANNER_APEX, SALESFORCE_SFDX_SCANNER_AURA, SALESFORCE_SFDX_SCANNER_LWC, SWIFT_SWIFTLINT, TSX_ESLINT, TYPESCRIPT_ES, TYPESCRIPT_PRETTIER
To receive reports as email, please set variable EMAIL_REPORTER_EMAIL


    
Listing all files in directory [/github/workspace], then filter with:
- File extensions: , .R, .RMD, .Rmd, .c, .c++, .cc, .cdxml, .clj, .cljc, .cljs, .coffee, .cpp, .cs, .cu, .cuh, .cxx, .dart, .edn, .env, .feature, .go, .gradle, .graphql, .groovy, .gvy, .h, .h++, .hcl, .hh, .hpp, .htm, .html, .hxx, .java, .json, .json5, .jsonc, .kt, .kts, .lua, .nf, .p6, .php, .pl, .pl6, .pm, .pm6, .pp, .proto, .ps1, .ps1xml, .psd1, .psm1, .psrc, .pssc, .py, .r, .raku, .rakumod, .rakutest, .rb, .rs, .rst, .scala, .smk, .sql, .t, .tex, .tf, .ts, .vb, .xml, .yaml, .yml
- File names (regex): Dockerfile, Jenkinsfile, Snakefile
- Excluding regex: docs/(css|js|lib|plugin)/**/*
- Excluding .gitignored files [0]: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/MegaLinter.py", line 108, in run
    self.collect_files()
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/MegaLinter.py", line 456, in collect_files
    filtered_files = utils.filter_files(
  File "/usr/local/lib/python3.9/site-packages/megalinter-0.1-py3.9.egg/megalinter/utils.py", line 80, in filter_files
    re.compile(filter_regex_exclude) if filter_regex_exclude else None
  File "/usr/local/lib/python3.9/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.9/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 26
```

**Comment by nvuillam** [comment]
I think there is an issue with your FILTER_REGEX_INCLUDE / EXCLUDE , please can you share your .mega-linter.yml ? ( or your github workflow yml )

**Comment by Bysmyyr** [comment]
Good catch, removing this one fixes that erro: 

FILTER_REGEX_EXCLUDE: docs/(css|js|lib|plugin)/**/*

**Comment by nvuillam** [comment]
Your regex value looks like a glob value, that's why it failed :)

You can check the validity of a regex using https://regex101.com/ :)

Maybe u'd like something like `(docs\/|css\/|js\/|lib\/|plugin\/)` (but it excludes a lot of folders, are you sure ? ^^ )
