### ISSUE TITLE
MegaLinter does not support @babel/eslint-parser

### ISSUE THREAD

**Issue by tayler-king** [megalinter/megalinter#1042]
**Describe the bug**
Linting should support @babel/eslint-parser, as babel-parser is outdated and deprecated.

**To Reproduce**

1. Configure ESLint to use the more-recommended, @babel/eslint-parser
2. Linting fails as the action doesn't support it

**Expected behavior**
Linting should support @babel/eslint-parser, as babel-parser is outdated and deprecated.

**Screenshots**
```console
Oops! Something went wrong! :(

ESLint: 8.2.0

Error: Failed to load parser '@babel/eslint-parser' declared in '--config': Cannot find module '@babel/eslint-parser'
Require stack:
- /github/workspace/.eslintrc.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at Object.resolve (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1088:46)
    at ConfigArrayFactory._loadParser (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3235:39)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3030:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2971:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadFile (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2781:16)
    at createCLIConfigArray (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3564:35)
```

**Comment by nvuillam** [comment]
PR on the way :)

In case of missing dependency, you can also install the ones of your package.json by defining

```yaml
PRE_COMMANDS:
  - continue_if_failed: false
    command: npm ci  # or "yarn" if you use yarn
    cwd: workspace
```

**Comment by tayler-king** [comment]
> PR on the way :)
> 
> 
> 
> In case of missing dependency, you can also install the ones of your package.json by defining PRE_COMMANDS in your `.mega-linter.yml`
> 
> 
> 
> ```yaml
> 
> PRE_COMMANDS:
> 
>   - continue_if_failed: false
> 
>     command: npm ci  # or "yarn" if you use yarn
> 
>     cwd: workspace
> 
> ```

Good to know, thanks!
