### ISSUE TITLE
Where goes the output file?

### ISSUE THREAD

**Issue by lokk3d** [megalinter/megalinter#711]
Hi :) 

I'm using this variable in the mega linter config file: 
PYTHON_PYLINT_ARGUMENTS:
  - --output-format=json:pylint.json

On the ERROR-PYTHON_PYLINT.log file, pylint correctly doesn't print the errors. 
I'm now trying to find the pylint.json file but I didn't found it on my local hard drive. 

What is the position of the output files of the linters when using mega-linter? 

Thanks for your help!

**Comment by nvuillam** [comment]
I think that according to [pylint doc](https://pylint.pycqa.org/en/latest/user_guide/output.html), it will creat an pylint.json file at the root of your repository

If you use Mega-Linter in CI, content of folder `report` is uploaded as artefact in Github actions / Gitlab CI / file.io reporter ...

So if you try  `--output-format=json:./report/pylint.json` , you should find pylint.json in the report folder :)

**Comment by lokk3d** [comment]
I'm currently getting this error: 

`--Error detail:
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.9/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/run.py", line 342, in __init__
    args = linter.load_command_line_configuration(args)
  File "/usr/local/lib/python3.9/site-packages/pylint/config/option_manager_mixin.py", line 336, in load_command_line_configuration
    (options, args) = self.cmdline_parser.parse_args(args=args)
  File "/usr/local/lib/python3.9/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/local/lib/python3.9/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/local/lib/python3.9/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/local/lib/python3.9/site-packages/pylint/config/option.py", line 176, in process
    return self.take_action(self.action, self.dest, opt, value, values, parser)
  File "/usr/local/lib/python3.9/optparse.py", line 805, in take_action
    self.callback(self, opt, value, parser, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pylint/config/option_manager_mixin.py", line 183, in cb_set_provider_option
    self.global_set_option(opt, value)
  File "/usr/local/lib/python3.9/site-packages/pylint/config/option_manager_mixin.py", line 187, in global_set_option
    self._all_options[opt].set_option(opt, value)
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 650, in set_option
    self._load_reporters()
  File "/usr/local/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 586, in _load_reporters
    open(reporter_output, "w", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './report/pylint.json'`


I have also created the file pylint.json to ensure that the file exists. 

I'm running with mega-linter-runner

My current config: 
DISABLE:
  - COPYPASTE # Uncomment to disable checks of abusive copy-pastes
  #- PYTHON
  - SPELL # Uncomment to disable checks of spelling mistakes
PRE_COMMANDS:
  - command: echo "Reading the config file..."
    cwd: "root"

PYTHON_PYLINT_ARGUMENTS:
  - --output-format=json:./report/pylint.json


Could you help me? :)

**Comment by nvuillam** [comment]
@lokk3d Maybe you can try `--output-format=json:./github/workspace/report/pylint.json`  ?
